   var GAME_LEVELS = [
  ["                                                                     o                                          y ",
   "   o                                                                                                          o y ",
   "           o                                                       yyyyy                                        y ",
   "  yyy                   o                                                                                       y ",
   "                                                                               yyyy                        yyyyyy ",
   "         yyyyy                                      oo                                                            ",
   "                           >                                                                                      ",
   "                                                                              >>>>>                               ",                                                                           
   "    ^            yyyyy                 y        o yyyyyy                                                          ",
   "                                       y          y                                       >>>>>                   ",
   "      >      o                         y       yyyy          >>>>>                 o                              ",
   "                                       y          y                                                               ",
   "          yyyyy                        y o        y                                                ^^^^^          ",
   "                                       y          y                                                               ",
   " @                                     yyyy       y                        >>>>>                                  ",
   " yyyy!!!yy                             y          y                                                               ",
   "    y!!!!y                             y        o y                                                               ",
   "    y!!!!y                             y          y                                                               ",
   "    yyyyyy                             y       yyyy                                                               ",
   "                                                  y                                                               ",
   "                                                  y                                                               ",
   "                                          >       y        xxx xxx xxxx          xxxxx  xx     xxxxxx x    xx  xx ",
   "  yyyyyyyyyyyyy   yyyyy                           y      yyyyyyyyyyyyy           yyyyyyyyy     yyyyyyyy    yyyyyy ",
   "                      y                           y                                                               ",     
   "              o       y                           y                                                               ",   
   "                      y                           y                                                               ",
   "        o   yyyyyy    y      >                    y                                                               ",
   "                      y                           y                                                               ",
   "       yyyy           yxxxxxxxxxxxxxxxxxxxxxxxxxxxy                                                               ",
   "                      yyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                               ",
   " yyyy                                                                                                             ",
   "             o                     o                      o              o                      o                 ",
   "                                                                  ?                 ?                             ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"],
  
  
  
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                   o                                                            ",
   "                                                                  yyy           ",
   "                  yyy                              yy     yyy    yy!yy          ",
   "                                    o o      yyyy               y!!!!!y         ",
   "                                                                 yy!yy          ",
   "                                   yyyyy                          yvy           ",
   "            yy                                                              yy  ",
   "  yy           o                          o o                                y  ",
   "  y    yy               o                                                    y  ",
   "  y         yyyyyy                        yyyyy                    o       o y  ",
   "  y         y                    o                                           y  ",
   "  y @       y          y                                         yyyyy       y  ",
   "  yyyy  yyyyyyy  yyyyyyyyyyyyyyy   yyyyyyyy  yyyyyyyyyy     yyyyyyyyyyyyyyyyyy  ",
   "     y!!y     y!!y             y   y                  y     y                   ",
   "     y!!y     yyyy             y!!!y                  y!!!!!y                   ",
   "     yyyy                      y!!!y                  y!!!!!y                   ",
   "                               yyyyy                  yyyyyyy                   ",
   "                                                                                ",
   "                                                                                "],
   
   
 
   
   

  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
   
   
   
   
   
  ["                                                  o                                                                          ",
   "                                                                                          o                                  ",
   "  o                              >>>>>>>                                                                                     ",
   "yyyyy                                                                                                                        ",
   "                    yyyy                                                                                                     ",
   "                                                        yyyyyyyyy  yyy  yyyyy                                    yyyyyyyyyy  ",
   "                                                        y!!y            y!!!y                                       o o o y  ",
   "                                                        y!!!y         yy!!!!y                                    yyyyyyyyyy  ",
   "             >>>>>                                      y!!!!y       y!!!!!!y                >>>>>>>>                        ",
   "                                                        y!!!!!y     y!!!!!!!y                                                ",
   "                                o                       y!!!!!!y   y!!!!!!!!y                                                ",
   "                                                        y!!!!!!!yoy!!!!!!!!!y       ^^^^^^^                                  ",
   "                             yyyyyyy                    y!!!!!!!yyy!!!!!!!!!y                                                ",
   "                                                        y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                                          o             y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                                                        y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                   >>>>>>                               yyyyyyyyyyyyyyyyyyyyy                 yyyyyyy                        ",
   "                                                         yyyyyyyyyyyyyyyyyyy                                                 ",
   "                                                          yyyyyyyyyyyyyyyyy                                                  ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                                                           y                                                                 ",
   "           yyyyyyyyyyy                 ^^^^^^              y                                                                 ",
   "                                                           yo                                         ^^^^^^                 ",
   "                                                           y                                                                 ",
   "                                                           yxx                                                               ",
   "                                                           yyyyyyy     y                                                     ",
   "                                                           !!!!!!y                                                           ",
   "                                                           !!!!!!yyyyyyyyy                                                   ",
   "  o                                                        !!!!!!!!!!!!!!y                   yyyyy                           ",
   "yyyyyy                                                     !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y       yyyyyy                                      ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                                                           y o o o o o o                                                     ",
   "                                                           y                                                                 ",
   "                                                           yyyyyyyyyyyyyyyy                                                  ",
   "                                                                                                                             ",
   "                        xxxx                      ?                                 xxxx              ?             xxxxxxxxx",
   "yyyyyyyyyyyyyyyyxxxyyyyyyyyyyyyyyy     yyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
   
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.eyports)
  module.eyports = GAME_LEVELS;
